- name: manager
  ip: 192.168.208.128
  cpus: 1
  mem: 512
  os: centos/7
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/centos-docker.yml
  size: 10GB  
- name: worker1
  ip: 192.168.208.130
  cpus: 1
  mem: 512
  os: centos/7
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/centos-docker.yml
  size: 10GB  
- name: worker2
  ip: 192.168.208.133
  cpus: 1
  mem: 512
  os: centos/7
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/centos-docker.yml
  size: 10GB  
