- name: manager
  ip: 100.0.0.10
  cpus: 2
  mem: 4096
  os: centos/7
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/centos-docker.yml
  size: 10GB
  manager: true
- name: worker1
  ip: 100.0.0.21
  cpus: 1
  mem: 2048
  os: centos/7
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/centos-docker.yml
  size: 10GB  
- name: worker2
  ip: 100.0.0.22
  cpus: 1
  mem: 2048
  os: centos/7
  docker: required
  provisioner: ansible
  playbook: infrastructure/provisioning/centos-docker.yml
  size: 10GB  
